apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

commonLabels:
  name: mariadb
  app: mariadb

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

secretGenerator:
  - name: mariadb-pwd
    type: Opaque
    envs:
      - env.txt
