kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.9
          args:
            - --api.insecure
            - --log.level=DEBUG
            - --accesslog

            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true

            - --entrypoints.websecure.address=:443

            - --entrypoints.synapse-federation.address=:448

            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=true
            # zero ssl resolver
            - --certificatesresolvers.default.acme.dnschallenge.provider=digitalocean
            - --certificatesresolvers.default.acme.dnschallenge.delaybeforecheck=0
            - --certificatesresolvers.default.acme.caserver=https://acme.zerossl.com/v2/DV90
            - --certificatesresolvers.default.acme.email=$(ACME_EMAIL)
            - --certificatesresolvers.default.acme.storage=/etc/traefik/acme/zerossl.json
            - --certificatesresolvers.default.acme.eab.kid=$(EAB_KID)
            - --certificatesresolvers.default.acme.eab.hmacencoded=$(EAB_KEY)
            # let's encrypt resolver
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=digitalocean
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
            - --certificatesresolvers.letsencrypt.acme.email=$(ACME_EMAIL)
            - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/letsencrypt.json
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: synapse-fed
              containerPort: 448
              hostPort: 448
            - name: admin
              containerPort: 8080
          env:
            - name: ACME_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: acme-email
                  key: email
            - name: DO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: digitalocean_token
            - name: EAB_KID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: eab_kid
            - name: EAB_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: eab_key
          volumeMounts:
            - mountPath: /etc/traefik/acme
              name: acme
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "10m"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: acme
          emptyDir: {}
