apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resource_definition.yaml
  - rbac.yaml
  - daemonset.yaml
  - router.yaml

configMapGenerator:
  - name: acme-email
    envs:
      - env.txt
