apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default


resources:
  - resource_definition.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - daemonset.yaml
  - service.yaml
configMapGenerator:
  - name: acme-email
    envs:
      - env.txt

secretGenerator:
  - name: secrets
    envs:
      - secret.txt
