apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`*`)
    kind: Rule
    middlewares:
    - name: redirectscheme
      namespace: default
    services:
    - name: synapse
      port: 8008
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: websecure
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`goatchat.ca`)
    kind: Rule
    services:
    - name: synapse
      port: 8008
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: synapse-fed
  namespace: default
spec:
  entryPoints:
    - synapse-federation
  routes:
  - match: Host(`goatchat.ca`)
    kind: Rule
    services:
    - name: synapse
      port: 8448
  tls:
    certResolver: letsencrypt
