apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photoprism

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - router.yaml

configMapGenerator:
  - name: photoprism
    envs:
      - env.txt

secretGenerator:
  - name: photoprism-secrets
    envs:
      - secret.txt
