apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: photoprism
  namespace: photoprism
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`photos.goatchat.ca`)
    kind: Rule
    services:
    - name: photoprism
      namespace: photoprism
      port: 80
  tls:
    certResolver: letsencrypt
