apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: small
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: med
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: large
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rook-ceph-block
