apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  selector:
    app: synapse
  ports:
    - name: api
      protocol: TCP
      port: 8008
    - name: federation
      protocol: TCP
      port: 8448
