apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
      name: postgres
      app: postgres
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: postgres
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: postgres
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pwd
              key: password
        image: postgres:12
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          name: 5432tcp02
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
          subPath: postgres
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "10m"
            memory: "100Mi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
