apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  name: kgnot

namesuffix: -kgnot

resources:
  - ../../base

patches:
  - path: router.yaml
  - target:
      version: v1beta1
      kind: VolumeSnapshot
      name: snapshot-ghost-store
    patch: |-
      - op: replace
        path: /spec/source/persistentVolumeClaimName
        value: ghost-store-kgnot

secretGenerator:
  - name: ghost-secrets
    type: Opaque
    behavior: replace
    envs:
      - secrets.txt

configMapGenerator:
  - name: ghost
    behavior: replace
    envs:
      - env.txt
