apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  name: kgnot

namesuffix: -kgnot

resources:
  - ../../base

patches:
  - path: router.yaml

secretGenerator:
  - name: ghost-db-pwd
    type: Opaque
    behavior: replace
    envs:
      - secrets.txt

configMapGenerator:
  - name: ghost
    behavior: replace
    envs:
      - env.txt
