apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-store
spec:
  dataSource:
    name: snapshot-ghost-store-kgnot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
