apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ghost
spec:
  entryPoints:
    - synapse-secure
  routes:
  - match: Host(`kgnot.ca`)
    kind: Rule
    services:
    - name: ghost-kgnot
      namespace: ghost
      port: 8080
  tls:
    certResolver: letsencrypt
