apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      containers:
        - image: ghost:4.21
          imagePullPolicy: Always
          name: ghost
          envFrom:
            - configMapRef:
                name: ghost
          env:
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-db-pwd
                  key: password
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: ghost
      volumes:
        - name: ghost
          persistentVolumeClaim:
            claimName: ghost-store
