apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - native
      restartPolicy: Always
      containers:
        - image: ghost:5.13.2
          imagePullPolicy: IfNotPresent
          name: ghost
          envFrom:
            - configMapRef:
                name: ghost
            - secretRef:
                name: ghost-secrets
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: ghost
          resources:
            limits:
              cpu: "500m"
              memory: '500Mi'
            requests:
              cpu: "10m"
              memory: '100Mi'
      volumes:
        - name: ghost
          persistentVolumeClaim:
            claimName: ghost-store
