apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

commonLabels:
  name: ghost
  app: ghost

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - router.yaml

secretGenerator:
  - name: ghost-db-pwd
    type: Opaque
    envs:
      - env.txt
