apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

commonLabels:
  name: ghost
  app: ghost

resources:
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - router.yaml
  #- snapshot.yaml

secretGenerator:
  - name: ghost-secrets
    type: Opaque
    envs:
      - secrets.txt

configMapGenerator:
  - name: ghost
    envs:
      - env.txt
