apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ghost
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`ghost.goatchat.ca`)
    kind: Rule
    services:
    - name: ghost
      namespace: ghost
      port: 8080
  tls:
    certResolver: letsencrypt
