apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: matrix-registration
spec:
  entryPoints:
    - synapse-secure
  routes:
  - match: Host(`goatchat.ca`) && PathPrefix(`/gate/`)
    kind: Rule
    services:
    - name: matrix-registration
      namespace: default
      port: 5000
  tls:
    certResolver: letsencrypt
